import { createHmac, timingSafeEqual } from "node:crypto";
import type { CheckoutResult, PaymentEvent, PaymentProvider } from "./provider";

const BASE_URL = "https://api.abacatepay.com/v2";

// Published verbatim in AbacatePay's docs as the key used to HMAC-sign every webhook payload:
// https://docs.abacatepay.com/pages/webhooks and https://docs.abacatepay.com/pages/webhooks/security
// (both pages show the identical constant). It is NOT a per-merchant secret — every AbacatePay
// integrator is documented to use this same value, so on its own it only proves the payload
// wasn't corrupted in transit; it does NOT prove a given callback belongs to *this* account
// (anyone who read the docs has this key too). Overridable via env in case AbacatePay rotates
// it or issues per-account keys in the future.
const ABACATEPAY_HMAC_PUBLIC_KEY =
  process.env.ABACATEPAY_HMAC_PUBLIC_KEY ??
  "t9dXRhHHo3yDEj5pVDYz0frf7q6bMKyMRmxxCPIPp3RCplBfXRxqlC6ZpiWmOqj4L63qEaeUOtrCI8P0VMUgo6iIga2ri9ogaHFs0WIIywSMg0q7RmBfybe1E5XJcfC4IW3alNqym0tXoAKkzvfEjZxV6bE0oG2zJrNNYmUCKZyV0KZ3JS8Votf9EAWWYdiDkMkpbMdPggfh1EqHlVkMiTady6jOR3hyzGEHrIz2Ret0xHKMbiqkr9HS1JhNHDX9";

/**
 * Pure, constant-time HMAC-SHA256 verification. AbacatePay signs the exact raw request-body
 * bytes and sends the digest **base64**-encoded (not hex) in the `X-Webhook-Signature` header.
 * Returns `false` whenever `signature` is null/absent — verification must never be skipped.
 */
export function verifyHmac(rawBody: string, signature: string | null, secret: string): boolean {
  if (!signature) return false;
  const expected = createHmac("sha256", secret).update(Buffer.from(rawBody, "utf8")).digest("base64");
  const a = Buffer.from(expected);
  const b = Buffer.from(signature);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/** Constant-time comparison for the URL-borne webhook secret (see PaymentProvider docs). */
export function constantTimeEqual(a: string | null | undefined, b: string): boolean {
  if (!a) return false;
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) return false;
  return timingSafeEqual(ab, bb);
}

type AbacateChargeLike = { id?: unknown; externalId?: unknown };
type AbacateSubscriptionLike = { id?: unknown; cancelledDueTo?: unknown };

const REFUND_EVENTS = new Set([
  "checkout.refunded",
  "checkout.disputed",
  "checkout.lost",
  "transparent.refunded",
  "transparent.disputed",
  "transparent.lost",
]);

function str(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

/**
 * Parses AbacatePay's v2 webhook envelope:
 *   { id, event, apiVersion, devMode, data: { checkout | transparent | subscription | ... } }
 *
 * Subscription events nest the charge under `data.checkout` and the subscription under
 * `data.subscription`. Deliberately tolerant of unknown/extra fields — AbacatePay's own docs
 * advise against fully validating the payload shape so future additions don't break this
 * endpoint.
 *
 * Docs: https://docs.abacatepay.com/pages/webhooks/events/subscriptions
 */
export function parseAbacateEvent(body: unknown): PaymentEvent | null {
  if (!body || typeof body !== "object") return null;
  const b = body as {
    event?: unknown;
    data?: {
      checkout?: AbacateChargeLike;
      transparent?: AbacateChargeLike;
      subscription?: AbacateSubscriptionLike;
    };
  };
  const event = str(b.event);
  if (!event) return null;

  const charge = b.data?.checkout ?? b.data?.transparent;
  const chargeId = str(charge?.id);
  const subscriptionId = str(b.data?.subscription?.id);

  switch (event) {
    case "subscription.completed": {
      // First payment. `externalId` is present here and ONLY here — this is our one chance
      // to record the subscription id against a user.
      if (!chargeId || !subscriptionId) return null;
      return {
        type: "paid",
        providerChargeId: chargeId,
        providerSubscriptionId: subscriptionId,
        externalId: str(charge?.externalId),
      };
    }
    case "subscription.renewed": {
      // The renewal checkout is generated by AbacatePay and carries `externalId: null`.
      // providerSubscriptionId is the only way back to a user; refuse the event without it
      // rather than silently dropping a payment.
      if (!chargeId || !subscriptionId) return null;
      return { type: "renewed", providerChargeId: chargeId, providerSubscriptionId: subscriptionId };
    }
    case "subscription.cancelled": {
      if (!subscriptionId) return null;
      return {
        type: "cancelled",
        providerSubscriptionId: subscriptionId,
        cancelledDueTo: str(b.data?.subscription?.cancelledDueTo),
      };
    }
    case "subscription.payment_failed": {
      if (!subscriptionId) return null;
      return { type: "payment_failed", providerSubscriptionId: subscriptionId };
    }
    case "checkout.completed":
    case "transparent.completed": {
      // A non-subscription one-off charge. Retained so any legacy/manual charge still works.
      if (!chargeId) return null;
      return { type: "paid", providerChargeId: chargeId, externalId: str(charge?.externalId) };
    }
    default: {
      if (REFUND_EVENTS.has(event)) {
        if (!chargeId) return null;
        return { type: "refunded", providerChargeId: chargeId };
      }
      return { type: "other" };
    }
  }
}

export class AbacatePayProvider implements PaymentProvider {
  readonly name = "abacatepay";

  constructor(
    private apiKey = process.env.ABACATEPAY_API_KEY ?? "",
    // AbacatePay checkouts reference a pre-created Product by id (POST /v2/products/create or
    // the dashboard) rather than accepting inline product fields at checkout time. The lifetime
    // -access product (price 11000 BRL cents) must be created once ahead of launch and its
    // returned `id` set here.
    private productId = process.env.ABACATEPAY_PRODUCT_ID ?? "",
    private hmacKey = ABACATEPAY_HMAC_PUBLIC_KEY,
    // The actual per-account authentication boundary: the secret configured when the webhook
    // was registered in the AbacatePay dashboard, echoed back as `?webhookSecret=` on every
    // callback URL. Required — verifyAndParseWebhook refuses to verify anything without it.
    private webhookUrlSecret = process.env.ABACATEPAY_WEBHOOK_SECRET ?? "",
  ) {}

  async createCheckout(input: {
    userId: string;
    amountCents: number;
    returnUrl: string;
    completionUrl: string;
  }): Promise<CheckoutResult> {
    if (!this.productId) {
      throw new Error(
        "ABACATEPAY_PRODUCT_ID is not configured. Create the lifetime-access product once " +
          "(AbacatePay dashboard or POST /v2/products/create with price=11000, currency=BRL) " +
          "and set the returned id as ABACATEPAY_PRODUCT_ID.",
      );
    }
    const res = await fetch(`${BASE_URL}/checkouts/create`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        // amountCents is not sent directly — AbacatePay charges the referenced product's own
        // fixed price. It's kept on the PaymentProvider interface for providers (Stripe, etc.)
        // that do take it directly.
        items: [{ id: this.productId, quantity: 1 }],
        // Card-only by product decision. To also accept PIX, add "PIX" here — but
        // keep the customer-facing copy in `app/page.tsx` and `components/paywall-cta.tsx`
        // in sync, since it names the accepted method.
        methods: ["CARD"],
        externalId: input.userId,
        returnUrl: input.returnUrl,
        completionUrl: input.completionUrl,
      }),
    });
    const json = (await res.json()) as {
      data?: { url?: string; id?: string };
      error?: unknown;
    };
    if (!res.ok || !json.data?.url || !json.data.id) {
      throw new Error(`abacatepay checkout failed: ${JSON.stringify(json.error ?? json)}`);
    }
    return { url: json.data.url, providerChargeId: json.data.id };
  }

  verifyAndParseWebhook(
    rawBody: string,
    signature: string | null,
    urlSecret?: string | null,
  ): PaymentEvent | null {
    // Gate 1 — the real authentication boundary. Refuse outright if we have no secret to check
    // against (misconfiguration must fail closed, never open).
    if (!this.webhookUrlSecret) return null;
    if (!constantTimeEqual(urlSecret, this.webhookUrlSecret)) return null;
    // Gate 2 — body-integrity check via HMAC.
    if (!verifyHmac(rawBody, signature, this.hmacKey)) return null;
    let parsed: unknown;
    try {
      parsed = JSON.parse(rawBody);
    } catch {
      return null;
    }
    return parseAbacateEvent(parsed);
  }
}
